### ISSUE TITLE
Sort replay time

### ISSUE THREAD

**Issue by FabriceFABS** [dansan/spring-replay-site#100]
Danchan,

OverKill* hosts managed by [CRT]AdolfSatan got +7 hours on CET time.
With this twisted-mind strategy, you will see only his hosts replays on the top of the SpringREPLAYS page. In general, it takes the 6 or 7 firsts places.
**You will never see anything else.**

In pics :
![screenshot10](https://cloud.githubusercontent.com/assets/6024913/19951270/2b0a796a-a15d-11e6-917f-dd63f2ccf319.png)
![screenshot11](https://cloud.githubusercontent.com/assets/6024913/19951285/47770136-a15d-11e6-9ef0-17574009abe5.png)
![screenshot12](https://cloud.githubusercontent.com/assets/6024913/19951289/4c729fa6-a15d-11e6-8ea0-d72ba26df32a.png)
Pic°2 shows most of the autohosts.

The only difference is 1 hour, with summer time, and in general, most of EU countries applies it.
Another instance, the replay on right of the "2" number, from host [BoS]Regicide (UK) got :
Date : 02.11.2016 22:25:40 (CET)
...
Uploaded by [BoS]Regicide on 02.11.2016 23:23:03 (CET)
...

Adding 7 hours is really pure fantasy.
So the idea is to sort replay with local SpringFILES's host time.
It would be the same, for all of us, and fair...

**Comment by abma** [comment]
IMHO it should be sorted by upload time

**Comment by dansan** [comment]
I wanted to be able to upload replays, and have them sorted correctly. Actually I wanted it to be sorted by match-end time...

But I see the problem and also that the usage pattern is: play, game end, click on link in lobby -> expect replay to be on top, and not be sorted by match-start time.

So I will change it to upload time.

**Comment by Yaribz** [comment]
In case you need it, SLDB has the true start / end times for all matches

**Comment by dansan** [comment]
Thank you.
For now I think the home page should work like a blog: newest posts (uploads) at top. I hope that meets the user expectation.
(SLDB is a little great data treasure :)
