### ISSUE TITLE
History graph not generated

### ISSUE THREAD

**Issue by vladmihaisima** [dansan/spring-replay-site#104]
After playing for the first time one game in one day (in this case it was evo and ba) the rating graphs are not generated (example: http://replays.springrts.com/player/5295/). This is true even after a couple of days. I did not play another time neither of them (might do int he future).

**Comment by dansan** [comment]
Were you logged in?
The user "malric" has privacy protection enabled. The rating history can only be seen by her/himself - when [logged into the replay site](http://replays.springrts.com/login/?next=/player/5295/).

**Comment by vladmihaisima** [comment]
Yes, was logged in before as well. Disabled the privacy protection (might be easier to check), still same behaviour. Checked again on BA teams (as there I played couple of games so there is "some" history), still no graph displayed.

Are they by any chance generated only once a month? Would not be a problem, but if there is no graph a message like "not enough data, come back on 1st of next month" might be better.

**Comment by dansan** [comment]
Looking at the win/loss data I can see the following:
* There is no relevant data for EvoRTS: the matches you have played were played on _test_ versions of EvoRTS - those are not counted.
* Regarding BA: my guess is that [SLDB](https://github.com/Yaribz/SLDB) the service that generates the TrueSkill data and graphs) simply does not have enough data yet. Play some more BA, and there will be data.
* For XTA there is enough data, and there are graphs.

OK - so I guess a "not enough data yet" picture is in order :)
