### ISSUE TITLE
Error 500 on new PA Def MOD

### ISSUE THREAD

**Issue by FabriceFABS** [dansan/spring-replay-site#105]
Could you fix it Daniel ?
![screenshot10](https://cloud.githubusercontent.com/assets/6024913/20721720/1cc8a752-b664-11e6-93ef-b665de26800b.png)

![screenshot11](https://cloud.githubusercontent.com/assets/6024913/20721558/7f6ebe10-b663-11e6-9c79-e1707c7fac06.png)

Thank you, regards
Fabrice

**Comment by dansan** [comment]
The mod needs a version string. Currently it's full name is "Planet Defense", so the replay site is unable to determine the version. I have installed a workaround, but please ask the game dev to add a version string.

**Comment by FabriceFABS** [comment]
Thx, Senna told me the MOD still in beta. Next version will get a version number.
