### ISSUE TITLE
502 Proxy error

### ISSUE THREAD

**Issue by FabriceFABS** [dansan/spring-replay-site#106]
502 Proxy Error, impossible to upload replay.

`<ProtocolError for replays.springrts.com/xmlrpc/: 502 Proxy Error>`
In spads console, also access to website with WEB client....etc

Thx....

**Comment by FabriceFABS** [comment]
Humm strange.... seems the replay has been uploaded.

It's not the first time I see that.
I remember, on May, 28th, impossible to manually upload replays, Error 500 or 502 on website, and neither autohost also.

**Comment by dansan** [comment]
There was a problem connecting to SLDB, and the frontend webserver did time out when waiting for the backend server.
