### ISSUE TITLE
enable https for replays.springrts.com

### ISSUE THREAD

**Issue by abma** [dansan/spring-replay-site#109]
as the password is sent plaintext via aether...

letsencrypt isn't rocket science :)

**Comment by dansan** [comment]
Thanks - just needed that little push :)

**Comment by specing** [comment]
Add a 80->443 permanent redirect as well.

**Comment by dansan** [comment]
Yes, that's a good idea.

Most autohost configurations use http zu upload replays.
I'll have to check, if they'll follow a redirect.
