### ISSUE TITLE
redirect port 80 to 443

### ISSUE THREAD

**Issue by dansan** [dansan/spring-replay-site#113]
Redirect all HTTP traffic to HTTPS site.
(from comment https://github.com/dansan/spring-replay-site/issues/109#issuecomment-403202357)

Check if autohost upload script will follow redirect first,

**Comment by specing** [comment]
@Yaribz

**Comment by dansan** [comment]
Code change was in c26832833ff12dc2987c94c46af64651f3e1d99e. I have asked @yaribz to update the upload script in the SPADS distribution.

The Apache configuration was modified to redirect everything except `/xmlrpc`, because the Python xmlrpc client cannot handle it.
