### ISSUE TITLE
add download link for engine

### ISSUE THREAD

**Issue by dansan** [dansan/spring-replay-site#115]
Download from http://api.springfiles.com/?springname=&filename=*104.0.1-743-g9e82927*&tag=&sdp=&metadata=on&nosensitive=on&category=

Try our JSON-API: http://api.springfiles.com/json.php?springname=&filename=*104.0.1-743-g9e82927*&tag=&sdp=&metadata=on&nosensitive=on&category=

**Comment by abma** [comment]
https:// please ;-)
