### ISSUE TITLE
automatically delete old replays

### ISSUE THREAD

**Issue by dansan** [dansan/spring-replay-site#116]
Replays older than 3 years should be automatically deleted.

→ Create a Django manage command and a daily cron job.

**Comment by dansan** [comment]
Django command is there now, but I just started the manual deletion of the first 99516 replays.
So I haven't created the cron job yet, to prevent it from starting while this massive deletion is running.
TODO: create cron job

**Comment by dansan** [comment]
OK  - old replays gone. I now created a daily cron job to run at 01:30 am.

**Comment by silentwings** [comment]
Thanks!
