### ISSUE TITLE
Error 500 on xmlrpc interface

### ISSUE THREAD

**Issue by TurBoss** [dansan/spring-replay-site#117]
https://replays.springrts.com/xmlrpc/ gives error 500

**Comment by TurBoss** [comment]
xmlrpc issue

**Comment by TurBoss** [comment]
xmlrpcserver is up and running and error 500 persist

**Comment by dansan** [comment]
Sorry, works again.
Error was caused by https://github.com/spring/uberserver/issues/348 / https://github.com/spring/uberserver/issues/349
