### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by woderfulworld** [dansan/spring-replay-site#118]
I cannot login to site. I checked 2 working accounts.
It's return "Your username and password didn't match. Please try again."

**Comment by springraaar** [comment]
i'm having the same issue with my spads autohosts, as explained here

https://springrts.com/phpbb/viewtopic.php?f=88&t=38995#p591170

I get the same message when manually trying to connect through the replays website with those accounts.

**Comment by dansan** [comment]
Sorry, works again.
Error was caused by https://github.com/dansan/spring-replay-site/issues/117.
