### ISSUE TITLE
srs_debug.log is spammed with Error deleting ... No such file or directory

### ISSUE THREAD

**Issue by abma** [dansan/spring-replay-site#121]
delete_old_replay_files.handle:43  Error deleting u'/var/www/servers/replays.springrts.com/spring-replay-site/srs/static/replays/20130101_001440_Tabula-v2__VJfu80_91.sdf.gz': [Errno 2] No such file or directory: '/var/www/servers/replays.springrts.com/spring-replay-site/srs/static/replays/20130101_001440_Tabula-v2__VJfu80_91.sdf.gz'

IMHO when it can't find the file it should update the db field:

https://github.com/dansan/spring-replay-site/blob/master/srs/management/commands/delete_old_replay_files.py#L44

-> remove the "else:" and make it always update the db

**Comment by abma** [comment]
as enhancement: search for orphaned files/replays :-)

**Comment by dansan** [comment]
Fixed in 32dfe3e5f7488d36edaa925a8c177dae9ce18b02
