### ISSUE TITLE
syntax error from daily cron job

### ISSUE THREAD

**Issue by abma** [dansan/spring-replay-site#128]
/etc/cron.daily/backup-dump-mysql:
  File "/var/www/servers/replays.springrts.com/spring-replay-site/manage.py", line 16
    ) from exc

**Comment by dansan** [comment]
Fixed the cronjob.
The Python 2 executable `/var/www/servers/replays-test.springrts.com/virtenv/bin/python` was still used. But the replay sites now runs on Python 3.8 and the new virtual env is `/home/replays/venv/`.

**Comment by dansan** [comment]
There were still errors. I didn't see the users crontab before.
Fixed it now with `sudo -u replays crontab -e`
