### ISSUE TITLE
images seems to be not deleted when the replay is deleted

### ISSUE THREAD

**Issue by abma** [dansan/spring-replay-site#129]
du -hs /var/www/servers/replays.springrts.com/spring-replay-site/srs/static/maps

22G

:-|

at a quick look, the oldest files in this dir are from 2012

**Comment by dansan** [comment]
Replays are never deleted, so the images are not deleted either.
The replays demo files are deleted.

I'll check how long it'd take to create a replays image on-demand. Then we could delete the old images and if anyone every looks at an old replay, the page would simply take a second longer to load.

**Comment by dansan** [comment]
OK, so when #130 is implemented, map files can simply be deleted when their replay demofiles are removed.

**Comment by dansan** [comment]
Deleted old map images.
Down from 22GB to 155MB :)
Unfortunately I also deleted the base images (from which the replay images are created), so I'll have to refetch them…

**Comment by dansan** [comment]
OK - I reuploaded the base images.

**Comment by dansan** [comment]
And now I also uploaded the `*_home.jpg` files ^.^
