### ISSUE TITLE
create replay map on demand if not on disk

### ISSUE THREAD

**Issue by dansan** [dansan/spring-replay-site#130]
In two quick tests on my notebook it took 0.08 seconds to create a replays individual map (with start boxes and start positions) from an already existing map file.

To allow deletion of the map files along with the replay demofiles (#129), and still keep the pages intact, handle missing replay maps.

When a replay page is accessed, check for the existence of the replays map file and create it on the fly if missing.

**Comment by abma** [comment]
very nice! :-)
