### ISSUE TITLE
How to patch content of eztables....

### ISSUE THREAD

**Issue by rosscosack** [dansan/spring-replay-site#131]
> The django-eztables packages views.py needs to be patched using eztables-GET.patch:
> 
> ```
> (srs) $ vi /home/replays/venv/lib/python3.8/site-packages/eztables/views.py
> #patch the content of eztables-GET.patch
> ```
> 
this has the venv named as venv instead of srs but that fine I can figure that out :)
Could you please provide more information on how to "patch the content of eztables-GET.patch"?
the file views.py contains no reference to this so I'm not sure where to start
Thanks

**Comment by dansan** [comment]
The problem with eztables is, that they don't work properly anymore (see #127).
But anyway, to apply a patch file run:
```
patch -p0 < eztables-GET.patch
```
But this patch is not good, as it includes the path into the virtualenv.
I think you're better of locating the referenced file (`eztables/views.py`) and  editing it directly (add the two lines that are prefixed with a `+` sign to the `post` and `get` methods).
