### ISSUE TITLE
TS stats based on 1217 battles but player only played 343

### ISSUE THREAD

**Issue by Keeermalec** [dansan/spring-replay-site#90]
Hi, my TS stats seem to take into account 1217 battles but I only played 343. Stats also indicate I have a win ratio of 47% while a manual check on the actual list gives 60%. I believe the stat engine may be including battles from some other player. Maybe this bug exists for others too.

http://replays.springrts.com/player/963048/

![screenshot-player aragorn spring replay site - chromium](https://cloud.githubusercontent.com/assets/16480041/12040120/682231e8-ae66-11e5-81d2-db0d859e7169.png)
![screenshot-player aragorn spring replay site - chromium-1](https://cloud.githubusercontent.com/assets/16480041/12040121/683c1e8c-ae66-11e5-9148-58e0443aa4e2.png)

**Comment by abma** [comment]
very likely related to #89

**Comment by dansan** [comment]
The statistics on the player and the match pages are not calculated using the data on the replay site, but by a service called SLDB (https://github.com/Yaribz/SLDB). It takes into account all matches it can see from the lobby - also matches that are not recorded on the replay site. It does also use the smurf database to associate multiple accounts that it thinks belong to the same user. If you wish to separate your data from that of another user, that ask in the springrts.com lobby server subforum for a SLDB account split. Not sure though who or if someone will do it, but you can try.

Anyway - the important information to take away from this thread is: **The replay site does not calculate any statistics about users at all!** It does only display what SLDB calculates.
