### ISSUE TITLE
group replays into folders /year[/month]/replay.sdfz

### ISSUE THREAD

**Issue by abma** [dansan/spring-replay-site#92]
this would reduce amount of files in a single folder / make it easier to manage.

imo replays should be deleted after some time to keep disk space usage at a reasonable limit.

**Comment by dansan** [comment]
@abma warning regarding rsync: moving 2018* and 2017* into subdirs.

**Comment by dansan** [comment]
uff... I made a typo and deleted all replays from 201701__ to 201711__... uploading from backup will take ages... maybe a good time to think about
> deleted after some time to keep disk space usage at a reasonable limit

**Comment by abma** [comment]
201701 ... 20170904 are on springrts.com...

**Comment by dansan** [comment]
Yes.
But 1st: I'm thinking to automatically delete all replays > 1/2y. I have all replays in the backup archive at home. If anyone needs an older one, they could PM me.
What do you think?
